med_store/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("store.urls"))
]

store/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name="store"
urlpatterns=[
    path("", views.my_login, name="login"),
    path("billing", views.billing, name="billing"),
    path("bills", views.bills, name="bills"),
    path("add", views.add, name="add"),
    path("view", views.view, name="view"),
    path("med", views.med, name="medicine")
]

store/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.base import Model
from django.db.models.deletion import CASCADE
from django.db.models.fields import AutoField, CharField, DateTimeField, FloatField, IntegerField
from django.db.models.fields.related import ForeignKey, ManyToManyField

# Create your models here.
class User(AbstractUser):
    def __str__(self):
        return f"{self.username}"

class manufacture(models.Model):
    id=models.AutoField(primary_key=True)
    name=CharField(max_length=64)
    address=CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"


class medicine(models.Model):
    mid=AutoField(primary_key=True)
    name=CharField(max_length=64)
    dosage=CharField(max_length=20)
    composition=CharField(max_length=64)
    stock=IntegerField()
    expiry=models.DateField()
    manu=ForeignKey(manufacture, on_delete=CASCADE, related_name="meds")
    price=FloatField(default=15)

    def __str__(self):
        return f"{self.name} {self.dosage}"

class patient(models.Model):
    pid=AutoField(primary_key=True)
    name=CharField(max_length=64)
    age=IntegerField()
    sex=CharField(max_length=6)
    phone=CharField(max_length=12)
    address=CharField(max_length=64)

    def __str__(self):
        return f"{self.name}"

class bill(models.Model):
    billid=AutoField(primary_key=True)
    pid=ForeignKey(patient, on_delete=CASCADE, related_name="patient")
    time=DateTimeField(auto_now_add=True)
    total=FloatField(default=0.0)

    def __str__(self):
        return f"{self.billid} at {self.time}"

class buy(models.Model):
    billid=ForeignKey(bill, on_delete=CASCADE, related_name="bill")
    mid=ForeignKey(medicine, on_delete=CASCADE, related_name="patients")
    qty=IntegerField()
    cost=FloatField()

    def __str__(self):
        return f"{self.billid}"

store/views.py
import random
import json
from django.db.models.fields import AutoField
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

# Create your views here.
from .models import manufacture, medicine, patient, buy, bill

meds=[]
qunti=[]

def my_login(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("store:billing"))
        else:
            return render(request, "store/login.html", {
                "message": "Invalid username or password."
            })
    else:
        return render(request, "store/login.html")

def billing(request):
    if request.method == "POST":
        name = request.POST["name"]
        age = request.POST["age"]
        gender = request.POST["gender"]
        phone = request.POST["phone"]
        address = request.POST["address"]

        p=patient()
        p.name=name
        p.age=age
        p.sex=gender
        p.phone=phone
        p.address=address
        p.save()

        pat=patient.objects.filter(name=name).first()

        bi=bill()
        bi.pid=pat
        bi.save()

        total=0

        for i in range(0,len(meds)):
            b=buy()
            b.billid=bi
            b.mid=meds[i]
            b.qty=qunti[i]
            pri=meds[i].price
            cost=(pri/10)*(qunti[i])
            b.cost=cost
            b.save()
            total+=cost

        bi.total=total
        bi.save()
        
        meds.clear()
        return HttpResponseRedirect(reverse("store:bills"))

    med=medicine.objects.all()
    return render(request, "store/billing.html", {
        "meds" : med
    })

def bills(request):
    b=reversed(bill.objects.all())
    return render(request, "store/bills.html", {
        "bills" : b
    })

def add(request):
    if request.method == "POST":
        name = request.POST["name"]
        dosage = request.POST["dosage"]
        manu = request.POST["manu"]
        composition = request.POST["composition"]
        stock = request.POST["stock"]
        expiry = request.POST["expiry"]

        man=manufacture.objects.filter(name=manu).first()

        med=medicine()
        med.name=name
        med.dosage=dosage
        med.manu=man
        med.composition=composition
        med.stock=stock
        med.expiry=expiry
        med.save()

        return HttpResponseRedirect(reverse("store:view"))

    manufactures=manufacture.objects.all()
    return render(request, "store/add.html", {
        "manufactures" : manufactures
    })

def view(request):
    meds=reversed(medicine.objects.all())
    return render(request, "store/view.html", {
        "meds" : meds
    })

@csrf_exempt
@login_required
def med(request):
    data=json.loads(request.body)
    medi=data["medicine"]
    qty=int(data["quantity"])

    med=medicine.objects.filter(name=medi).first()
    med.stock-=qty
    med.save()

    meds.append(med)
    qunti.append(qty)

    return JsonResponse({"message": "Email sent successfully."}, status=201)

store/templates/store/add.html
{% extends "store/layout.html" %}

{% block body %}
<div class="med_form">
    <p class="sign" align="center">Add Meds</p>
    <form name="med" action="{% url 'store:add' %}" method="POST">
    {% csrf_token %}
        <input type="text" placeholder="Name" name="name" class="form_text">
        <input type="text" placeholder="Dosage" name="dosage" class="form_text">
        <select name="manu" class="form_text">
            <option value="">Manufacturer</option>
            {% for manu in manufactures %}
                <option value="{{manu.name}}">{{ manu.name }}</option>
            {% endfor %}
        </select>
        <input type="text" name="composition" placeholder="Composition" class="form_text">
        <input type="text" name="stock" placeholder="Stock" class="form_text">
        <input type="date" name="expiry" placeholder="Expiry" class="form_text bottom_margin">
        <input type="submit" value="ADD" class="btn submit" align="center">
    </form>
</div>
{% endblock %}

store/templates/store/billing.html
{% extends "store/layout.html" %}

{% block body %}
<div class="bill_form">
    <p class="sign" align="center">BILLING</p>
    <form name="med" action="{% url 'store:billing' %}" method="POST">
    {% csrf_token %}
        <input type="text" placeholder="Name" name="name" class="bill_text">
        <input type="text" placeholder="Age" name="age" class="bill_text">
        <div class="row bill_radio">
            <h5 class="margin_right margin_top">Gender: </h5>
                Male<input type="radio" name="gender" value="male" class="margin_right">
                Female<input type="radio" name="gender" value="female" class="margin_top">
        </div>
        <input type="text" name="phone" placeholder="Phone no." class="bill_text">
        <input type="text" name="address" placeholder="Address" class="bill_text bottom_margin">
        <p class="inner_sign">Add meds</p>
        <div id="dynamic"></div>
        <select name="add-med" id="med" class="inner_text">
            <option value="">Medicine</option>
            {% for med in meds %}
                <option value="{{med.name}}">{{med.name}}</option>
            {% endfor %}
        </select>
        <input type="text" placeholder="Quantity" id="qty" name="qty" class="inner_text">
        <button class="btn bill_btn" onclick="return false" id="add">Add</button>
        <input type="submit" value="BILL" class="btn bill_submit" align="center">
    </form>
</div>
{% endblock %}

store/templates/store/bills.html
{% extends "store/layout.html" %}

{% block body %}
{% for bill in bills%}
    <div class="bills_main">
        <div class="bills_head row col-lg-12">
            <div class="col-lg 3">
                <h5>Name: {{bill.pid.name}}</h5>
                <h5>Age: {{bill.pid.age}}</h5>
                <h5>Sex: {{bill.pid.sex}}</h5>
                <h5>Address: {{bill.pid.address}}</h5>
            </div>
            <div class="col-lg-6"></div>
            <div class="col-lg-3">
                <h5>Bill id : {{ bill.billid}}</h5>
                <h5>Date : {{ bill.time.date}}</h5>
                <h5>Time : {{ bill.time.time}}</h5>
            </div>
        </div>
        <div class="col-lg-12 row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <table class="table">
                    <thead class="thead-primary">
                        <tr>
                            <th class="col-lg-4">Medicine</th>
                            <th class="col-lg-2" style="text-align: center;">Quantity</th>
                            <th class="col-lg-2" style="text-align: center;">cost</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for med in bill.bill.all %}
                            <tr>
                                <td>{{med.mid.name }} - {{ med.mid.dosage}}</td>
                                <td style="text-align: center;">{{med.qty}}</td>
                                <td style="text-align: center;">{{med.cost}}</td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <td></td>
                            <td style="text-align: center;"><h5>Total : </h5></td>
                            <td style="text-align: center;"><h5>{{bill.total}}</h5></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-lg-2"></div>
        </div>
    </div>
{% endfor %}
{% endblock %}

store/templates/store/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Med_Store{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'store/my.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">    
    </head>
    <body>
        <ul class="nav menu-bar">
            <li class="nav-item menu-name">
                <h1>Med-Store</h1>
            </li>
            
            <li class="nav-item menu-item">
                <a class="nav-link" href="{% url 'store:billing' %}">BILLING</a>
            </li>
            <li class="nav-item menu-item">
                <a class="nav-link" href="{% url 'store:bills' %}">BILLS</a>
            </li>
            <li class="nav-item menu-item">
                <a class="nav-link" href="{% url 'store:view' %}">VIEW MED</a>
            </li>
            <li class="nav-item menu-item">
                <a class="nav-link" href="{% url 'store:add' %}">ADD MED</a>
            </li>
            
        </ul>
        {% block body %}
        {% endblock %}
        <script src="{% static 'store/myscript.js' %}"></script>
    </body>
</html>

store/templates/store/login.html
{% load static%}

<html>

<head>
  <link rel="stylesheet" href="{% static 'store/my.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  
  <title>Sign in</title>
</head>

<body>
    <div class="main">
        <p class="sign" align="center">Sign in</p>
        <form class="form1" method="POST" action="{% url 'store:login' %}">
            {% csrf_token %}
            <input class="un " name="username" type="text" align="center" placeholder="Username">
            <input class="pass" name="password" type="password" align="center" placeholder="Password">
            <input type="submit" class="btn submit" align="center" value="sign in">
            <p class="forgot" align="center"><a href="#">{{message}}</p>
        </form>    
                
    </div>
     
</body>

</html>

store/templates/store/view.html
{% extends "store/layout.html" %}

{% block body %}
<div class="row bottom_margin">
    <div class="col-lg-1"></div>
    <div class="col-lg-10">
        <h2 class="text-center mb-4 heading">Medicines</h2>
        <div class="table-wrap">
            <table class="table">
                <thead class="thead mythead">
                    <tr>
                        <th>Name</th>
                        <th>Composition</th>
                        <th>Dosage</th>
                        <th>Stock</th>
                        <th>Expiry</th>
                        <th>Manufacturer</th>
                        <th>Cost</th>
                    </tr>
                </thead>
                <tbody>
                    {% for med in meds%}
                        <tr class="border">
                            <th scope="row" class="scope">{{ med.name }}</th>
                            <td class="odd">{{ med.composition }}</td>
                            <td>{{ med.dosage}}</td>
                            {% if med.stock < 30 %}
                                <td class="odd low">{{ med.stock }}</td>
                            {% else %}
                                <td class="odd">{{ med.stock }}</td>
                            {% endif %}
                            <td>{{ med.expiry }}</td>
                            <td class="odd">{{ med.manu }}</td>
                            <td>{{ med.price }}</td>
                        </tr>
                    {% endfor %}    
                </tbody>
            </table>
        </div>
    </div>        
    <div class="col-lg-1"></div>
</div>
{% endblock %}